force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Signoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Previous_Task__c.field-meta.xml
<CustomField>
    <fullName>Previous_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Task</fullName>
            </value>
            <value>
                <fullName>Planning Phase</fullName>
            </value>
            <value>
                <fullName>Construction Work</fullName>
            </value>
            <value>
                <fullName>Completion Step</fullName>
            </value>
            <value>
                <fullName>Contract End</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectTriggerHelper.cls
public class ProjectTriggerHelper {
    public static void showErrorOnProjectInsert(List<Project__c> projectList){
        for(Project__c project : projectList){
            if(project.Status__c != null){
                project.Status__c.addError('You can not choose this field from here');
            }
        } 
    }
    public static void showErrorOnProjectUpdate(List<Project__c> projectList, Map<Id, Project__c> projectMap, Map<Id, Project__c> projectOldMap){
        for(Project__c project : projectList){
        	if(projectMap.get(project.Id).Status__c != projectOldMap.get(project.Id).Status__c){
       			projectMap.get(project.Id).Status__c.addError('You can not change this field from here');
            }
    	}
    }
    public static void toCreateProjectTask(List<Project__c> projectList){
        List<Project_Task__c> probjectTaskListToInsert = new List<Project_Task__c>();
        //List<Id> ProjctTaskIdList = new List<Id>();
        
        for(Project__c project : projectList){
            probjectTaskListToInsert.add(new Project_Task__c(Type__c='New Task', Project__c =Project.Id));
            probjectTaskListToInsert.add(new Project_Task__c(Type__c='Planning Phase', Project__c =Project.Id));
            probjectTaskListToInsert.add(new Project_Task__c(Type__c='Construction Work', Project__c =Project.Id));
            probjectTaskListToInsert.add(new Project_Task__c(Type__c='Completion Step', Project__c =Project.Id));
            probjectTaskListToInsert.add(new Project_Task__c(Type__c='Contract End', Project__c =Project.Id));
        }
       	INSERT probjectTaskListToInsert;
        for(Integer index=1; index < probjectTaskListToInsert.size(); index++){
            if(probjectTaskListToInsert.get(index).Type__c != 'New Task'){
                probjectTaskListToInsert.get(index).Previous_Task__c = probjectTaskListToInsert.get(index-1).Id;
            }
        }
    	if(probjectTaskListToInsert.size() > 0){
        	upsert probjectTaskListToInsert;
        }
    }
}