force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Brand_VOC__c.field-meta.xml
<CustomField>
    <fullName>Brand_VOC__c</fullName>
    <label>Brand VOC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Positive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Pay_Rate__c.field-meta.xml
<CustomField>
    <fullName>Pay_Rate__c</fullName>
    <label>Pay Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat rate</fullName>
            </value>
            <value>
                <fullName>Gift Cart</fullName>
            </value>
            <value>
                <fullName>Other fill in text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Pay_Rate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pay_Rate_Amount__c</fullName>
    <label>Pay Rate Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProgramTriggerTest.cls
/*
	Created by : Syed mehdi
	Created Date : Feb-03-2023

*/
@isTest
public class ProgramTriggerTest {
    @TestSetup
    public static void createTestData(){
    	Account account = new account(Name = 'Test Account');
    	insert account;
    }
    @isTest
    private static void testProgramTrigger(){
        Account account = [Select Id, Name From Account Limit 1];
        Id recordTypeId = Schema.SObjectType.Program__c.getRecordTypeInfosByName().get('Test Record Type').getRecordTypeId();
    	List<Program__c> programList = new List<Program__c>();
        
        programList.add(new Program__c(Name = 'Test Program', RecordTypeId = recordTypeId,  Account__c = account.Id, Brand_VOC__c ='Neutral', Pay_Rate__c = 'Flat rate', Pay_Rate_Amount__c = 5000));	
        insert programList;
        Assert.areEqual(programList[0].Id != null, true);
        
        programList[0].Brand_VOC__c = 'Positive';
        ProgramTriggerHelper.counter = false;
        update programList;
        Assert.areEqual( 'Positive',programList[0].Brand_VOC__c);
        ProgramTriggerHelper.counter = false;
        delete programList;
    }
}