force-app/main/default/objects/Gantt_Project__c/Gantt_Project__c.object-meta.xml
<CustomObject>
    <label>Gantt Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gantt Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprint__c/fields/Gantt_Project__c.field-meta.xml
<CustomField>
    <fullName>Gantt_Project__c</fullName>
    <label>Gantt Project</label>
    <referenceTo>Gantt_Project__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SearchableController.cls
public class SearchableController {
	@AuraEnabled 
    public static List<Sobject> searchContact(String value, String objectName, Id projectId, String owner){
        
        String fields = 'Id, Name ';  
        String filter = ' WHERE Name LIKE \''+ value + '%\' ORDER BY Name';
        if(objectName == 'Sprint__c' && owner == ''){
        	filter = ' WHERE Gantt_Project__c = \''+ projectId +'\' AND Name Like \'' + value + '%\' ORDER BY Name';    
        }else if(owner == 'User' && objectName == 'Sprint__c'){
            objectName = owner;
        }
        String query = 'SELECT '+ fields + ' FROM ' + objectName + ' ' + filter ;
        system.debug('query ' + query);
        return Database.query(query);
        
        /*if(objectName == 'contact'){
        	return [SELECT Id, Name FROM Contact WHERE Name LIKE: + value + '%' ORDER BY Name];
        }else if(objectName =='gantt project'){
        	return [SELECT Id, Name FROM Gantt_Project__c WHERE Name LIKE: + value + '%' ORDER BY Name];
        }else if(objectName == 'sprint' && owner == ''){
            return [SELECT Id, Name FROM Sprint__c WHERE Gantt_Project__c =: projectId AND Name Like : + value + '%' ORDER BY Name];
        }else if(owner == 'owner' && objectName == 'sprint'){
            return [SELECT Id, Name FROM User WHERE Name LIKE : + value + '%' ORDER BY Name];
        }else{
            return null;
        }*/
    }
}