force-app/main/default/objects/Order_Shipping__e/Order_Shipping__e.object-meta.xml
<CustomObject>
    <label>Order Shipping</label>
    <pluralLabel>Order Shippings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order_Shipping__e/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Shipping__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PublishingPlatformEvent.cls
public class PublishingPlatformEvent {
    public PublishingPlatformEvent(){
		List<Order_Shipping__e> orderShippingList = new List<Order_Shipping__e>();
        Order_Shipping__e orderShipping = new Order_Shipping__e(Order_Number__c= '1234', Status__c = 1);
        orderShippingList.add(orderShipping);
        List<Database.SaveResult> result = EventBus.publish(orderShippingList);
        for(Database.SaveResult sr : result){
            if(sr.isSuccess()){
                System.debug('Event is Published Sucessfully ');
            }else{
                for(Database.Error err : sr.getErrors()){
                    System.debug('Error returned: ' +err.getStatusCode());
                }
            }
        }
    }
}